//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicWallpaperRetriever.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DynamicWallpaperRetriever.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the provided save path is a folder..
        /// </summary>
        internal static string ErrorDownloadFolderPath {
            get {
                return ResourceManager.GetString("ErrorDownloadFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot download file: .
        /// </summary>
        internal static string ErrorDownloadPrefix {
            get {
                return ResourceManager.GetString("ErrorDownloadPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the provided URL is incorrect..
        /// </summary>
        internal static string ErrorDownloadUrlFormat {
            get {
                return ResourceManager.GetString("ErrorDownloadUrlFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no URL is given..
        /// </summary>
        internal static string ErrorDownloadUrlNull {
            get {
                return ResourceManager.GetString("ErrorDownloadUrlNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the provided HTML color code is not formatted correctly (e.g. #FFFFFF)..
        /// </summary>
        internal static string ErrorHtmlColorCodeFormat {
            get {
                return ResourceManager.GetString("ErrorHtmlColorCodeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set background color: .
        /// </summary>
        internal static string ErrorSetBackgroundColorPrefix {
            get {
                return ResourceManager.GetString("ErrorSetBackgroundColorPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  the provided monitor index/ID is incorrect..
        /// </summary>
        internal static string ErrorSetMonitorMalformed {
            get {
                return ResourceManager.GetString("ErrorSetMonitorMalformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid command: .
        /// </summary>
        internal static string FaultyCommandErrorPrefix {
            get {
                return ResourceManager.GetString("FaultyCommandErrorPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: .
        /// </summary>
        internal static string FaultyCommandWarningPrefix {
            get {
                return ResourceManager.GetString("FaultyCommandWarningPrefix", resourceCulture);
            }
        }
    }
}
